name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: AirWalk-Digital/github-action-dockerhub@master
    - name: Build and pushthe Docker image
      secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
 
